name = "master-widget"
main = "masterWidget.js"
compatibility_date = "2025-07-22"
account_id = "b70c309587ed8ba2bfa06320792ea457"
workers_dev = true

# CORS configuration to allow embedding on client websites
[env.production]
routes = [
  { pattern = "widget.inexasli.com/*", zone_name = "inexasli.com" }
]
